install:
  - make dev_env
language: python
python:
  - '3.8'
script:
  - make lint
  - make unit

services:
  - docker

app_name: nyu-devops-alumniconnect

after_success:
  - heroku container:login
  - heroku container:push web -a {{ app_name }}
  - heroku container:release web -a {{ app_name }}