install:
  - make dev_env
language: python
python:
  - '3.8'
script:
  - make lint
  - make unit

services:
  - docker

after_success:
  - heroku container:login
  - heroku container:push web -a nyu-devops-alumniconnect
  - heroku container:release web -a nyu-devops-alumniconnect