install:
  - make dev_env
language: python
python:
  - '3.8'
script:
  - make lint
  - make unit
  - eval $(aws ecr get-login --region us-east-2)
  - docker-compose build
  - docker images
  - docker tag org/web:latest 943278698679.dkr.ecr.us-east-2.amazonaws.com/org/web:latest
  - docker push 943278698679.dkr.ecr.us-east-2.amazonaws.com/org/web:latest
# deploy:
#   provider: heroku
#   api_key:
#     secure: UxAu6zpQv69mprhx4wqRomO8wQrWNz7NsNRfITIqYQ0zgYhMZLJoOH7Q5RZGtKPAWr9SPlzgOdO8mQyDPagDajNrohpq8GTXLmP4x9bSi4K7mnMskmz5N3LUuDFw/ZUhpKgkLvqPyIEF+4eZs8lqom3Pd/6CaI/y14rDIPDeT3/fcu1JKHL2dJ5O+/LfmZXiro55+xdp+BEVo/G9idKTIJbRQ7Rgs7Wqp6Ea2JsosP9GugJx/lnPnNOuGFmIxbN8mkx8lyc0Rrsp5oXksjlef7k+WeIzvmGklPhcjqWxhAs47FwnFGFC9aX8dGlKU/BzaZZ8DdxIu9Ii3UbmumUfkZTtq3xSjh0VWrkrSf6j8mLeX+0Vj3RpnIdM1h+tXJGBS/njx2gWJ5iQ1fMC2PB9kwC8H0zVBkW4UMGWwgNkDi80VnZLxkwS/wp6qQvGFDcju10Aao6OsdmfTdacsXzb1E1+ZGqzchNDQCgrUDOt5ZY3CpK5i+a2hFh9yxzDam1AKe5eaYKnr+e/z8iJFGoASJz+AJ85AEG0j00UpkpdEcZbwHaPGQCW+d1mqJsQDPnA7a1TC+OE9+y96S0BWW9deLjM7s9Uu+ZrpmzDUTp8nKlvHyYqRATs0+DZL3BszLVoixDmK4P0kl28rS+AkqC00iOGzAMz6F/a0u221L/qCdY=
#   app: nyu-devops-alumniconnect
#   on:
#     repo: Vivian004/Alumni-Connect
services:
  - docker

# after_success:
#   - heroku login
#   - heroku git:remote -a nyu-devops-alumniconnect
#   - git push heroku master

before_install:
  - pip install awscli

after_success:
  - heroku container:login
  - heroku container:push web -a nyu-devops-alumniconnect
  - heroku container:release web -a nyu-devops-alumniconnect
  
env:
  global:
  - secure: Gw27OFfiVQbUDwMw2bK5GtdXQCszFsUnfWznqSkd9Qj8pGiBwkaMM+onTZgbclLm/VIfRMH6jpjzv1ZdO/2a8T10ZPnFq6eocUpjpBbBMb6MvZiVExXtm1XgMZiWNBSbPlhIxzQxOkQ/YovS+4kpAQgXDpASG6tRZ8VCA9gDff4p/c6xxN4pRtafCxzaBHRnOReqazaNyN64e8QIBQxMt7/xiBdZn92nONB+KosoimNa1k7XiR6VY1jZSkFBHUnMMw050WN11TVSMAzLzcjDog5SloczUYDmbqQvwwDrFD/MCB+XZ1RxqkgJ4Rsyyyq2GGKuBUqxfFrLJNH/tAMGlN+NS2U2Td0ylgD0D+Yeiuw0Z77la+3eqQjJlFHgBVBOSBpIDOVKwDutx87ERB8cIbWa0XzE2y/UHxEipXTQmmVxrFJEbWgjPIHXOZ6J9EAebxEBVp2WOJrtBJHbup/uBM3VL40V1JQKVmfYA6FQEVjSipiIlri8sm3wmLTIDLJObGHtaaBNXhtrE6qUYs6SrxucYkoIPB+FWXqK3nQIYWTk4p6miOwN7ynhQ7r/+26GK+0JQiH1RQQfVjqxzCtR67PFp5TkQMPfVSGU+efNXVenEkU1tH8am0Lp4mXmU+mv75tJq9erUg6GnNXswfBkydaqyuIVkJTR20UH+odENuE=
  - secure: YxvhRQf7If65ZUyp2Ed4Vm9eOVgssS2wGiNa82xgLOWEz1iN5xKYwgYO+EDDD2E6AkNo5gNF3+jNUpmTsRGNotLlJYTTvxTbUremfYmiTePLmM9u9dNFKXzlKeQAT30dFvr78u7vf0VvyCd8VOflbO5PvBpxenx05scJobwQFc5TVaXXkyv+UCZ8GIIXj/MjAwAU8nYwzhyZ8AMlyI/rZbiYTIuFib3WrChkApUiP84wY/2Mwk9n/4xlWXio+RDN/HDW8v75dOX1qprSl10wl3uJzbOT23/ylONbPl3ZfQVTj2uS0EmG/TKtStZL3AwDYN3bB2nX53LIkc5tnDsAtX+ej7MRMxrkkLxg6xdxMcjaEbK9DNPc5n8ZHNZO/r16SAw/OJJrrt8RxkX6VYJpJQ3e/X+GU0ifeXgtEFjnlSVk4ljR3LRSxaaM3M6DEFaIuyRFZi/m1F2cZ2tqIIMSRRs9InNmRzyI2fSVnUkkNiPJ8NAMYHQixLB30F7veVYAGQHHWo5XJcrQu/QsjkNSUjKbFyRoQeYdeMZ0SXxEcS+Zo6OiJy8zmzKBJAeZ0z+drzTAQR3t9YWZtlhQdPkZGhQVY+8vIizVLFxkUalGZBhBQBFA6LY93fUiZkTXfr0iCZE/zzRcnKjkTAbzt4zONpSo01LrxLr8p3kRiV276Pw=
